### ISSUE TITLE
"Boneshaker" Duplicate in Spellbook

### ISSUE THREAD

**Issue by Horologus** [Holic75/KingmakerRebalance#79]
When playing through the Main Campaign, I noticed that Harrim has two Boneshaker spells in his spellbook - one from his domain, and one from the "default" Cleric list. Those are treated separately, and can't be stacked on the action bar. This wasn't the case before.

https://imgur.com/a/Ev6235O

**Comment by Holic75** [comment]
This is not a bug. It is required to make other classes with domain spells work correctly (generally any class whose class spell level is different from domain spell level), the spells otherwise behave as though they were the same (for example for the purpose of spell specialization and similar feats).

**Comment by Horologus** [comment]
This is a bug, since in previous versions, or in the vanilla version, the domain/regular version of a spell would stack in the quick slots.
